### ISSUE TITLE
Does wq build work with #115?

### ISSUE THREAD

**Issue by simonwinter** [wq/wq.app#119]
Hi there,

I'm running the react/material UI approach as documented in PR #115

**TL;DR**

Is `wq build` not necessary with this version (assuming `r.js` is no longer necessary)?

---

When I run `wq build 0.0.0` I find a missing dependency issue:

```bash
$ wq build 0.0.0
/Users/.../starterkit/venv/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
Application version: 0.0.0
src/data/templates.json: 4 objects collected from ../templates
public/css/themes.css compiled from scss/themes.scss
Optimizing with r.js...
Error: Error: Error: /Users/.../starterkit/app/node_modules/@types/q/styled-jsx not found
    at Object.statSync (<anonymous>:80:24)
```

This doesn't look like anything related to @wq as such, possibly a dependency? @type/q/styled-jsx simply is not a package that exists.

Essentially it hangs at `Optimizing with r.js...`

This is my package.json:

```json
{
  "name": "starterkit",
  "version": "0.0.0",
  "proxy": "http://localhost:8000/",
  "private": true,
  "dependencies": {
    "@wq/app": "^1.3.0-a1-dev78.gbc6db35",
    "@wq/mapbox": "^1.3.0-a1-dev78.gbc6db35",
    "@wq/material": "^1.3.0-a1-dev78.gbc6db35",
    "react-scripts": "^3.4.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

Here's my `wq.yml`

```yaml
init:
    css: public/css

# Generate JSON fixtures
collectjson:
     # Mustache Templates
     -
        paths:
             - ../templates
        type: html
        output: src/data/templates.json
        json:
            indent: 4

# Compile jQuery Mobile themes from SCSS
scss:
    indir: scss
    outdir: public/css

# Update version.txt & JS module
setversion:
    filename: ../version.txt

# Generate web icons
icons:
    source: public/icon-1024.png
    outdir: public/
    filename: icon-{size}.png
    size: web

# Optimize with r.js
optimize:
    appDir: .
    baseUrl: src
    dir: ../htdocs
    skipDirOptimize: true
    removeCombined: true
```
